partum_inventory/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^', include('pis_com.urls')),
    re_path(r'^product/', include(('pis_product.urls', 'product'),namespace='product'),),
    re_path(r'^retailer/', include(('pis_retailer.urls', 'retailer'), namespace='retailer')),
    re_path(r'^sales/', include(('pis_sales.urls', 'sales'), namespace='sales')),
    re_path(r'^ledger/', include(('pis_ledger.urls','ledger'), namespace='ledger')),
    re_path(r'^expense/', include(('pis_expense.urls','expense'), namespace='expense')),
    re_path(r'^employee/', include(('pis_employees.urls','employee'), namespace='employee')),
    re_path(r'^supplier/', include(('pis_supplier.urls','supplier'), namespace='supplier')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pis_com/urls.py
from django.urls import path, include,re_path


from pis_com.views import HomePageView
from pis_com.views import LoginView
from pis_com.views import LogoutView
from pis_com.views import (
    CreateCustomer, CustomerTemplateView, CustomerUpdateView, CreateFeedBack)
from pis_com.views import RegisterView, ReportsView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='index'),
    re_path(r'^reports/$', ReportsView.as_view(), name='reports'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    #path('api/', include('pis_com.api_urls', namespace='com_api')),
    re_path(r'^api/',CreateCustomer.as_view(),name='create_customer'),

    re_path(r'^customer/create/$', CustomerTemplateView.as_view(), name='customers'),

    re_path(r'^customers/$', CustomerUpdateView.as_view(), name='update_customer'),
    re_path(r'^customer/(?P<pk>\d+)/update$', RegisterView.as_view(), name='register'),
    re_path(r'^register/$', CreateFeedBack.as_view(), name='create_feedback'),
]

pis_product/urls.py
from django.urls import re_path


from pis_product.views import ProductItemList
from pis_product.views import ProductDetailList
from pis_product.views import AddNewProduct
from pis_product.views import AddProductItems
from pis_product.views import PurchasedItems
from pis_product.views import ExtraItemsView
from pis_product.views import ClaimedProductFormView
from pis_product.views import ClaimedItemsListView
from pis_product.views import StockItemList
from pis_product.views import AddStockItems
from pis_product.views import StockOutItems
from pis_product.views import StockDetailView
from pis_product.views import StockInListView
from pis_product.views import StockOutListView
from pis_product.views import ProductUpdateView
from pis_product.views import StockInUpdateView

from pis_product.logs_view import DailyStockLogs, MonthlyStockLogs


urlpatterns = [
    re_path(r'^items/list/$', ProductItemList.as_view(), name='items_list'),
    re_path(r'^item/(?P<pk>\d+)/detail/list/$',ProductDetailList.as_view(),name='item_details'),
    re_path(r'^retailer/(?P<retailer_id>\d+)/add/$',AddNewProduct.as_view(),name='add_product'),
    re_path(r'^item/(?P<product_id>\d+)/add/$',AddProductItems.as_view(),name='add_product_items'),
    re_path(r'^items/purchased/$', PurchasedItems.as_view(),name='purchased_items'),
    re_path(r'^items/extra/purchased/$', ExtraItemsView.as_view(),name='purchased_extra_items'),
    re_path(r'^items/claimed/$', ClaimedProductFormView.as_view(),name='claimed_items'),
    re_path(r'^items/claimed/list/$', ClaimedItemsListView.as_view(),name='claimed_items_list'),
    re_path(r'^retailer/(?P<retailer_id>\d+)/add/$',AddNewProduct.as_view(),name='add_product'),
    re_path(r'^stock/items/list/$', StockItemList.as_view(), name='stock_items_list'),
    re_path(r'^stock/item/(?P<product_id>\d+)/add/$',AddStockItems.as_view(),name='add_stock_items'),
    re_path(r'^stock/item/(?P<product_id>\d+)/out/$',StockOutItems.as_view(),name='stock_out_items'),
    re_path(r'^stock/item/(?P<product_id>\d+)/detail/$',StockDetailView.as_view(),name='stock_detail'),
    re_path(r'^(?P<product_id>\d+)/stock/in/$',StockInListView.as_view(),name='stockin_list'),
    re_path(r'^(?P<product_id>\d+)/stock/out/$',StockOutListView.as_view(),name='stockout_list'),
    re_path(r'^(?P<pk>\d+)/update/$',ProductUpdateView.as_view(),name='update_product'),
    re_path(r'^(?P<pk>\d+)/stockin/update/$',StockInUpdateView.as_view(),name='update_stockin'),

    # Logs
    re_path(r'^stock/logs/daily/$', DailyStockLogs.as_view(),name='daily_stock_logs'),
    re_path(r'^stock/logs/monthly/$', MonthlyStockLogs.as_view(),name='monthly_stock_logs'),
]

pis_retailer/urls.py
from django.urls import path, include,re_path

from pis_retailer.views import RetailerProductsAPI


urlpatterns = [
    re_path(r'^(?P<retailer_id>\d+)/products/$',RetailerProductsAPI.as_view(),name='retailer_products'),
]

templates/products/add_product.html
{% extends 'base.html' %}
{% block submenu_add_product %}active{% endblock %}
{% block menu_product %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'product:stock_items_list' %}"><button type="button" id="back-product" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Product List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ request.user.retailer_user.retailer.name }} Product</h3>
        <span class="item_list_error text-center" style="color:red; display:none">item is already exist</span>
        <div class="panel-body">
            <form class="form-horizontal add-product-form" action="{% url 'product:add_product' retailer_id=request.user.retailer_user.retailer.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Product Name</strong></label>
                        <span class="product-name-error" style="color:red; display:none">The field is required</span>
                        <input type="text" class="form-control product_name" name="name"   placeholder="Product Name"><br>
                        <label><strong>Brand Name</strong></label>
                        <span class="brand-name-error" style="color:red; display:none">The field is required</span>
                        <input type="text" class="form-control brand_name" name="brand_name" placeholder="Brand Name"><br>
                        <label><strong>Unit Type</strong></label>
                        <input type="text" class="form-control unit_type" name="unit_type" placeholder="Unit Type" list="unit-list">
                        <datalist id="unit-list">
                            <option value="Kilogram"></option>
                            <option value="Gram"></option>
                            <option value="Litre"></option>
                            <option value="Quantity"></option>
                        </datalist>
                        <br>
                        <label><strong>Bar Code</strong></label>
                        <input type="number" class="form-control bar_code" name="bar_code" placeholder="Bar Code">
                        <span style="color: #68dff0">For example: 1234567899876 (13 digit number)</span><br><br>
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" id="save" class="btn btn-primary product-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Product</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!--scrpit for field validation-->

<script>

    $ (document).ready(function(){
        $ (".product-submit-btn").on('click', function(){
            $(this).addClass('disabled');
            $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
            var error= false;

            if ($('.product_name').val() == ""){
                $(".product-name-error").show();
                error = true;
            }
            else {
                $(".product-name-error").hide();
            }

            if ($('.brand_name').val() == ""){
                $(".brand-name-error").show();
                error = true;
            }
            else {
                $(".brand-name-error").hide();

            }

            if ($('.consumer_price').val() == ""){
                $(".consumer-name-error").show();
                error = true;
            }
            else {
                $(".consumer-name-error").hide();
            }
            if ($('.available_item').val() == ""){
                $(".available-name-error").show();
                error = true;
            }
            else {
                $(".available-name-error").hide();

            }

            if (error == true) {
                return;
            } else {
                $.get('{% url 'retailer:retailer_products' retailer_id=request.user.retailer_user.retailer.id %}', function(data, status){
                    $.each(data.retailer_products, function(index, value){
                        if ($('.product_name').val() == value.product_name && $('.brand_name').val() == value.brand_name && {{ request.user.retailer_user.retailer.id }} == value.retailer){
                            $('.item_list_error').show();
                            error = true;
                            return false;
                        }
                    });
                    if (error == false) {
                        $('.add-product-form').submit();
                    }
                      else
                 {
                     $(this).removeClass('disabled');
                     $(this).html('Add product');
                     return;
                 }

                });

            }
        });

        $('.product_name').keyup(function(){
            $('.product-name-error').hide();
        });

        $('.brand_name').keyup(function(){
            $('.brand-name-error').hide();
        });

        function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }

        $('.consumer_price').keyup(function(){
            $('.consumer-name-error').hide()
            checkDec(this);
        });
        function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }

        $('.available_item').keyup(function(){
            $('.available-name-error').hide()
            checkDec(this);
        });
        function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }

    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script>
$('#back-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('.form-control').click (function () {
    $('.list-error').hide();
    checkDec(this);

});
    </script>
<script>
$('#save').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 1000);
});

$('.form-control').click (function () {
    $('.list-error').hide();
    checkDec(this);

});
    </script>

{% endblock %}

templates/products/claimed_product.html
{% extends 'base.html' %}
{% block menu_product %}active{% endblock %}
{% block submenu_purchased_claimeditems %}active{% endblock %}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'product:add_product' retailer_id=request.user.retailer_user.retailer.id %}"><button type="button" id="add-product" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add Product </button></a>
        <a href="{% url 'product:stock_items_list' %}"><button type="button" id="back-product" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Product List</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">Claimed items</h3>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-12">
                        <span class="customer_error" style="color: red; display: none" > This Field is requreid</span>
                        <label><strong>Customer</strong></label>
                        <input type="text" class="form-control customer" name="customer" placeholder="Customer" list="customer-list">
                        <label><strong>Customer List</strong></label>
                        <datalist id="customer-list">
                            {% for customer in customers %}
                                <option data-id="{{ customer.id }}" value="{{ customer.customer_name }}">{{ customer.customer_phone }}</option>
                            {% endfor %}
                        </datalist>
                        <br>
                        <span class="product_error"style="color: red; display: none" >This field is Required</span>
                        <label><strong>product Name</strong></label>
                        <input type="text" class="form-control product" name="product" placeholder="Product" list="product-list">
                        <label><strong>product list</strong></label>
                        <datalist id="product-list">
                            {% for product in products %}
                                <option data-id="{{ product.id }}" value="{{ product.name }}">{{ product.brand_name }}</option>
                            {% endfor %}
                        </datalist>
                        <br>
                        <span class="claimed_item_error" style="color: red; display: none" >This field is Required</span>
                        <label><strong>Claimed Item</strong></label>
                        <input type="number" class="form-control claimed_items" name="claimed_items" placeholder="Claimed Items"><br>
                        <span class="claimed_amount_error" style="color: red; display: none" >This field is Required</span>
                        <label><strong>Claimed Amount</strong></label>
                        <input type="text" class="form-control claimed_amount"  name="claimed_amount"  placeholder="Claimed Amount"><br>
                        <button type="button" class="btn btn-primary claimed-btn" style="float: right">Claimed</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $('.claimed-btn').on('click', function () {
            var error = false;
            if ($('.customer').val ()== ""){
                $('.customer_error').show();
                error = true;
            }
            else
            {
                $('.customer_error').hide();
            }
            if ($('.product').val() =="") {
                $('.product_error').show();
                error = true;
            }
            else {
                $('.product_error').hide();
            }
            if ($('.claimed_items').val()== ""){
                $('.claimed_item_error').show();
                error = true;
            }
            else{
                $('.claimed_item_error').hide();
            }
            if ($('.claimed_amount').val()== "" ) {
                $('.claimed_amount_error').show();
                error = true;
            }
            else {
                $('.claimed_amount_error').hide()
            }

            if (error == true) {
                return;
            }

            var product_val = $('.product').val();
            var product_id = $('#product-list [value="' + product_val + '"]').data('id');

            var customer_val = $('.customer').val();
            var customer_id = $('#customer-list [value="' + customer_val + '"]').data('id');

            $.post('{% url "product:claimed_items" %}', {
                product: product_id,
                claimed_items: $('.claimed_items').val(),
                customer: customer_id,
                claimed_amount: $('.claimed_amount').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }, function (result, status) {
                window.location.href = '{% url "product:items_list" %}';
            });
        });

        $('.customer').keyup(function () {
            $('.customer_error').hide();
        });

        $('.product').keyup(function () {
            $('.product_error').hide();
        });

        $('.claimed_items').keyup(function () {
            $('.claimed_item_error').hide();
        });

        $('.claimed_amount').keyup(function () {
            $('.claimed_amount_error').hide();
            checkDec(this);
        });
        function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
    </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script>
$('#back-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('#add-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('.form-control').click (function () {
    $('.list-error').hide();
    checkDec(this);

});
    </script>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}
{% block menu_product %}active{% endblock %}
{% block submenu_list_items %}active{% endblock %}
{% block content %}
    <div class="col-md-12">
            <br>
            <a href="{% url 'product:add_product' retailer_id=request.user.retailer_user.retailer.id %}"><button type="button" id="add-product" class="btn btn-primary"  id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add Product </button></a>
            <br><br><br>
            <div class="content-panel table-responsive">
                <table class="table table-striped table-bordered table-advance table-hover item-table">
                    <h2 class="text-center">Product List</h2>
                    <div class="input-group custom-search-form col-md-4" style="left: 5px">
                        <input type="text" class="form-control search-product" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <hr>
                    <thead>
                    <tr>
                        <th class="text-center"><i class="fa fa-bullhorn"></i> Item Name</th>
                        <th class="text-center"><i class="fa fa-question-circle"></i> Brand Name</th>
                        <th class="text-center"><i class=" fa fa-bookmark"></i> Unit</th>
                        <th class="text-center"><i class=" fa fa-bookmark"></i> Available Items</th>
                        <th class="text-center"><i class=" fa fa-edit"></i> Purchased Items</th>
                        <th class="text-center"><i class=" fa fa-edit"></i> Bar Code</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="product-table-body text-center">
                    {% for item in products %}
                        <tr>
                            <td><a href="{% url 'product:item_details' pk=item.id %}">{{ item.name}}</a></td>
                            <td class="#">{{ item.brand_name }}</td>
                            <td class="#">{{ item.unit_type }}</td>
                            <td>{{ item.product_available_items|floatformat:-2 }}</td>
                            <td>{{ item.product_purchased_items|floatformat:-2 }}</td>
                            <td>{{ item.bar_code}}</td>
                            <td>
                                <a href="{% url 'product:add_product_items' product_id=item.id %}"><button class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></button></a>
                                <a href="{% url 'product:item_details' pk=item.id %}"><button class="btn btn-success btn-xs"><i class="fa fa-eye"></i></button></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <script>
            $(document).ready(function(){
              $(".search-product").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $(".product-table-body tr").filter(function() {
                  $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
              });
            });
        </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script>
$('#add-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('.form-control').click (function () {
    $('.list-error').hide();
    checkDec(this);

});
    </script>

{% endblock %}

templates/products/stock_list.html
{% extends 'base.html' %}
{% block menu_product %}active{% endblock %}
{% block submenu_list_items %}active{% endblock %}
{% block content %}
    <div class="col-md-12">
            <br>
            <a href="{% url 'product:add_product' retailer_id=request.user.retailer_user.retailer.id %}"><button type="button" id="add-product" class="btn btn-primary"  id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add Product </button></a>
            <br><br><br>
            <div class="content-panel table-responsive">
                <table class="table table-striped table-bordered table-advance table-hover item-table">
                    <h2 class="text-center">Stock Products</h2>
                    <div class="row" style="padding: 5px">
                        <div class="col-lg-4">
                            <input type="text" class="form-control name_search" placeholder="Search by Item Name ..." value="{{ search_value_name }}">
                        </div>
                        <div class="col-lg-2">
                            <button class="btn btn-primary search">Search</button>
                        </div>
                    </div>
                    <hr>
                    <thead>
                    <tr>
                        <th class="text-center">Item Name</th>
                        <th class="text-center">Brand Name</th>
                        <th class="text-center">Unit Type</th>
                        <th class="text-center">Total Items</th>
                        <th class="text-center">Available Items</th>
                        <th class="text-center">Purchased Items</th>
                        <th class="text-center">Bar Code</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="product-table-body text-center">
                    {% for item in object_list %}
                        <tr>
                            <td><a href="{% url 'product:item_details' pk=item.id %}">{{ item.name}}</a></td>
                            <td class="#">{{ item.brand_name }}</td>
                            <td class="#">{{ item.unit_type }}</td>
                            <td>{{ item.total_items|floatformat:-2 }}</td>
                            <td>{{ item.product_available_items|floatformat:-2 }}</td>
                            <td>{{ item.product_purchased_items|floatformat:-2 }}</td>
                            <td>{{ item.bar_code }}</td>
                            <td>
                                <a href="{% url 'product:update_product' pk=item.id %}"><button class="btn btn-success btn-xs"><i class="fa fa-edit"></i></button></a>
                                <a href="{% url 'product:stockin_list' product_id=item.id %}"><button class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></button></a>
                                <a href="{% url 'product:stockout_list' product_id=item.id %}"><button class="btn btn-danger btn-xs" title="Stock Out"><i class="fa fa-minus"></i></button></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if paginator.page_range|length > 1 %}
                    <div class="text-center">
                        <ul class="pagination">
                            <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'product:stock_items_list' %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                            <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'product:stock_items_list' %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function () {
            $('.search').on('click', function () {
                var url = '{% url "product:stock_items_list" %}';
                window.location.href  = url + '?' + 'name=' + $('.name_search').val();
            });
        });
    </script>
<script>
$('#add-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});
</script>
{% endblock %}

templates/products/stockin_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-12">
        <br>
        <a href="{% url 'product:add_stock_items' product_id=product.id %}"><button type="button" id="stock-in" class="btn btn-primary" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Stock In</button></a>
        <a href="{% url 'product:stock_items_list' %}"><button type="button" id="add-product" class="btn btn-primary" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Products List</button></a>
        <br><br><br>
        <div class="content-panel table-responsive">
            <h1 class="text-center">{{ product.name|title }} <small>{{ product.brand_name|title }}</small> | Stock In</h1><br>
            <table class="table table-striped table-advance table-hover item-table table-bordered">
                <thead>
                <tr>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Buying Price / Item</th>
                    <th class="text-center">Total Buying Amount</th>
                    <th class="text-center">Selling Price / Item</th>
                    <th class="text-center">Total Selling Amount</th>
                    <th class="text-center">Added Date</th>
                    <th class="text-center">Expiry Date</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody class="product-table-body text-center">
                {% for stockin in object_list %}
                    <tr>
                        <td>{{ stockin.quantity|floatformat:-2 }} </td>
                        <td class="#">{{ stockin.buying_price_item|floatformat:-2 }}</td>
                        <td class="#">{{ stockin.total_buying_amount|floatformat:-2 }}</td>
                        <td>{{ stockin.price_per_item|floatformat:-2 }}</td>
                        <td>{{ stockin.total_amount|floatformat:-2 }}</td>
                        <td>{{ stockin.dated_order }}</td>
                        <td>{{ stockin.stock_expiry }}</td>
                        <td>
                            <a href="{% url 'product:update_stockin' pk=stockin.id %}"><button class="btn btn-primary btn-xs"><i class="fa fa-edit"></i></button></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if paginator.page_range|length > 1 %}
                <div class="text-center">
                    <ul class="pagination">
                        <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'product:stockin_list' product_id=product.id %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                        <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'product:stockin_list' product_id=product.id %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
<script>
$('#stock-in').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('#add-product').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>
{% endblock %}