partum_inventory/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^', include('pis_com.urls')),
    re_path(r'^product/', include(('pis_product.urls', 'product'),namespace='product'),),
    re_path(r'^retailer/', include(('pis_retailer.urls', 'retailer'), namespace='retailer')),
    re_path(r'^sales/', include(('pis_sales.urls', 'sales'), namespace='sales')),
    re_path(r'^ledger/', include(('pis_ledger.urls','ledger'), namespace='ledger')),
    re_path(r'^expense/', include(('pis_expense.urls','expense'), namespace='expense')),
    re_path(r'^employee/', include(('pis_employees.urls','employee'), namespace='employee')),
    re_path(r'^supplier/', include(('pis_supplier.urls','supplier'), namespace='supplier')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pis_com/urls.py
from django.urls import path, include,re_path


from pis_com.views import HomePageView
from pis_com.views import LoginView
from pis_com.views import LogoutView
from pis_com.views import (
    CreateCustomer, CustomerTemplateView, CustomerUpdateView, CreateFeedBack)
from pis_com.views import RegisterView, ReportsView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='index'),
    re_path(r'^reports/$', ReportsView.as_view(), name='reports'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    #path('api/', include('pis_com.api_urls', namespace='com_api')),
    re_path(r'^api/',CreateCustomer.as_view(),name='create_customer'),

    re_path(r'^customer/create/$', CustomerTemplateView.as_view(), name='customers'),

    re_path(r'^customers/$', CustomerUpdateView.as_view(), name='update_customer'),
    re_path(r'^customer/(?P<pk>\d+)/update$', RegisterView.as_view(), name='register'),
    re_path(r'^register/$', CreateFeedBack.as_view(), name='create_feedback'),
]

pis_supplier/urls.py
from django.urls import re_path
from pis_supplier.views import(
    AddSupplier, SupplierList, SupplierStatementList, AddSupplierStatement,
    SupplierStatementUpdate,StatementPayment)


urlpatterns = [
    re_path(r'^add/$', AddSupplier.as_view(), name= 'add_supplier'),
    re_path(r'^lists/$', SupplierList.as_view(), name= 'list_supplier'),
    re_path(r'^statements/list/(?P<pk>\d+)/$',SupplierStatementList.as_view(),name='list_supplier_statement'),
    re_path(r'^statement/payment/(?P<pk>\d+)/$',StatementPayment.as_view(),name='payment'),
    re_path(r'^add/statements/(?P<pk>\d+)/$',AddSupplierStatement.as_view(),name='add_supplier_statement'),
    re_path(r'^update/statements/(?P<pk>\d+)/$',SupplierStatementUpdate.as_view(),name='update_supplier_statement')
]

templates/supplier/add_supplier.html
{% extends 'base.html' %}
{% block submenu_create_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="#"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Supplier List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center"> Add Supplier</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'supplier:add_supplier' %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Name</strong></label>
                        <span class="name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control name" name="name" placeholder="Name"><br>
                        <label><strong>Address</strong></label>
                        <span class="father_name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control father_name" name="address" placeholder="Addreess"><br>
                        <label><strong>Phone Number</strong></label>
                        <span class="mobile-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control mobile" name="phone" placeholder="Phone"><br>
                        <label><strong>Mobile no</strong></label>
                        <input type="text" class="form-control mobile" name="mobile_no" placeholder="Mobile"><br>

                        <button type="submit" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Supplier</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/supplier/add_supplier_statement.html
{% extends 'base.html' %}
{% block submenu_create_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="#"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Name</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center"> Add Statement</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'supplier:add_supplier_statement' pk=supplier.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Name</strong></label>
                        <span class="name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control name" name="supplier_name" value="{{ supplier }}" placeholder="{{ supplier }}" readonly><br>
                        <label><strong>Supplier Amount</strong></label>
                        <span class="father_name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control father_name" name="supplier_amount" placeholder="Total Amount"><br>
                        <label><strong>Payment Amount</strong></label>
                        <span class="mobile-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control mobile" name="payment_amount" placeholder="Payable Amount"><br>
                        <label><strong>description no</strong></label>
                        <input type="text" class="form-control mobile" name="description" placeholder="Description"><br>
                        <label><strong>Date</strong></label>
                        <input type="date" class="form-control mobile" name="date" placeholder="Date"><br>

                        <button type="submit" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Statement</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/supplier/list_supplier.html
{% extends 'base.html' %}
{% block submenu_list_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br>
            <a href="{% url 'supplier:add_supplier' %}"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Create Supplier</button></a>
            <br><br>
        <div class="col-md-4">
<!--                    <button type="button" class="btn btn-primary print-invoice-btn mt" onclick="PrintInvoice('print-invoice')">Print Details</button><br>-->
                </div>
            <div class="content-panel table-responsive">
                <h2 class="text-center">Supplier List</h2>
                <div class="input-group custom-search-form col-md-6 pull-left" style="left: 5px">
                <input type="text" class="form-control search-order" placeholder="Search...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
            </div>
                <div class="print-invoice" id="print-invoice">

            <div class="pull-right col-md-6">
                <h3 class="text-right" ><b>Total Remaining:<span style="color:red">{{ total_remaining_amount|floatformat:'-2' }}</span></b></h3>
                </div>
                <hr>
                <table class="table table-striped table-advance table-hover item-table table-bordered">
                    <thead>
                    <tr>
                        <th class="text-center"><i class="fa fa-gavel"></i> S.No</th>
                        <th class="text-center"><i class="fa fa-gavel"></i> Name</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Remaining Amount</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Address</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Phone</th>
                        <th class="text-center"> Mobile</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="order-table-body text-center">
                    {% for supplier in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ supplier.name }}</td>
                        <td>{{ supplier.supplier_remaining_amount }}</td>
                        <td>{{ supplier.address }}</td>
                        <td>{{ supplier.phone }}</td>
                        <td>{{ supplier.mobile_no }}</td>
                        <td>
{#                            <a href="#"><button class="btn btn-danger btn-xs" title="Delete"><i class="fa  fa-trash-o"></i></button></a>#}
                            <a href="{% url 'supplier:list_supplier_statement' pk=supplier.id %}"><button class="btn btn-success btn-xs" title="All Statements"><i class="fa  fa-info"></i></button></a>
{#                            <a href="#"><button class="btn btn-info btn-xs"><i class="fa fa-bar-chart-o"></i></button></a>#}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>

<script>
 function PrintInvoice(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
 }
</script>

{% endblock %}

templates/supplier/list_supplier_statement.html
{% extends 'base.html' %}
{% block submenu_list_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br>
            <a href="{% url 'supplier:list_supplier' %}"><button type="button" id="statement" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing"> Supplier List</button></a>
            <a href="{% url 'supplier:add_supplier_statement' pk=supplier.id %}"><button type="button" id="statement" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Create Statement</button></a>
            <a href="{% url 'supplier:payment' pk=supplier.id %}"><button type="button" id="statement" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Payment</button></a>

            <br><br>
        <div class="col-md-4">
<!--                    <button type="button" class="btn btn-primary print-invoice-btn mt" onclick="PrintInvoice('print-invoice')">Print Details</button><br>-->
                </div>
            <div class="content-panel table-responsive">
                <h2 class="text-center">{{ supplier }} | Statement List</h2><div class="input-group custom-search-form col-md-4" style="left: 5px">
                <input type="text" class="form-control search-order" placeholder="Search...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
            </div>
            <div class="print-invoice" id="print-invoice">

            <div class="pull-right col-md-6">
                <h4 class="text-right"><b>Total Remaining: <span style="color:red"> {{ supplier_total_remaining_amount|floatformat:'-2' }}</span></b></h4>
                </div>
                <hr>
                <table class="table table-striped table-advance table-hover item-table table-bordered">
                    <thead>
                    <tr>
                        <th class="text-center"><i class="fa fa-gavel"></i> S.No</th>
                        <th class="text-center"><i class="fa fa-gavel"></i> Name</th>
                        <th class="text-center"><i class="fa fa-gavel"></i> Supplier Amount</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Payment Amount</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Remaining Amount</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Description</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Date</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="order-table-body text-center">
                    {% for statement in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ statement.supplier.name }}</td>
                        <td>{{ statement.supplier_amount }}</td>
                        <td>{{ statement.payment_amount }}</td>
                        <td>{{ statement.remaining_amount }}</td>
                        <td>{{ statement.description }}</td>
                        <td>{{ statement.date }}</td>
                        <td>
                            <a href="{% url 'supplier:update_supplier_statement' pk=statement.id %}"><button class="btn btn-warning btn-xs" title="Edit"><i class="fa  fa-edit"></i></button></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
<script>
 function PrintInvoice(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
 }
</script>
{% endblock %}

templates/supplier/payment.html
{% extends 'base.html' %}
{% block submenu_create_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <br>
    <div class="content-panel">
        <h3 class="text-center"> Add Payment | {{supplier.name}}</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'supplier:payment' pk=supplier.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <span class="name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="hidden" class="form-control name" name="supplier" value="{{ supplier.id }}" placeholder="{{ supplier }}" readonly><br>
                        <label><strong>Payment Amount</strong></label>
                        <span class="mobile-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control mobile" name="payment_amount" placeholder="Payable Amount"><br>
                        <label><strong>description no</strong></label>
                        <input type="text" class="form-control mobile" name="description" placeholder="Description"><br>
                        <label><strong>Date</strong></label>
                        <input type="date" class="form-control mobile" name="date" placeholder="Date"><br>

                        <button type="submit" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Statement</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/supplier/update_supplier_statement.html
{% extends 'base.html' %}
{% block submenu_create_supplier %}active{% endblock %}
{% block menu_supplier %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center"> Update Statement |{{supplier.name}}</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'supplier:update_supplier_statement' pk=object.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <span class="name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="hidden" class="form-control name" name="supplier" value="{{ object.supplier.id }}" placeholder="{{ object.supplier.id }}" readonly><br>
                        <label><strong>Supplier Amount</strong></label>
                        <span class="father_name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control father_name" name="supplier_amount" placeholder="{{object.supplier_amount}}" value="{{object.supplier_amount}}"><br>
                        <label><strong>Payment Amount</strong></label>
                        <span class="mobile-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control mobile" name="payment_amount" placeholder="{{object.payment_amount}}" value="{{object.payment_amount}}"><br>
                        <label><strong>description no</strong></label>
                        <input type="text" class="form-control mobile" name="description" placeholder="{{object.description}}" value="{{object.description}}"><br>
                        <label><strong>Date</strong></label>
                        <input type="date" class="form-control mobile" name="date" placeholder="Date"><br>

                        <button type="submit" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Statement</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}