partum_inventory/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^', include('pis_com.urls')),
    re_path(r'^product/', include(('pis_product.urls', 'product'),namespace='product'),),
    re_path(r'^retailer/', include(('pis_retailer.urls', 'retailer'), namespace='retailer')),
    re_path(r'^sales/', include(('pis_sales.urls', 'sales'), namespace='sales')),
    re_path(r'^ledger/', include(('pis_ledger.urls','ledger'), namespace='ledger')),
    re_path(r'^expense/', include(('pis_expense.urls','expense'), namespace='expense')),
    re_path(r'^employee/', include(('pis_employees.urls','employee'), namespace='employee')),
    re_path(r'^supplier/', include(('pis_supplier.urls','supplier'), namespace='supplier')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pis_com/urls.py
from django.urls import path, include,re_path


from pis_com.views import HomePageView
from pis_com.views import LoginView
from pis_com.views import LogoutView
from pis_com.views import (
    CreateCustomer, CustomerTemplateView, CustomerUpdateView, CreateFeedBack)
from pis_com.views import RegisterView, ReportsView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='index'),
    re_path(r'^reports/$', ReportsView.as_view(), name='reports'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    #path('api/', include('pis_com.api_urls', namespace='com_api')),
    re_path(r'^api/',CreateCustomer.as_view(),name='create_customer'),

    re_path(r'^customer/create/$', CustomerTemplateView.as_view(), name='customers'),

    re_path(r'^customers/$', CustomerUpdateView.as_view(), name='update_customer'),
    re_path(r'^customer/(?P<pk>\d+)/update$', RegisterView.as_view(), name='register'),
    re_path(r'^register/$', CreateFeedBack.as_view(), name='create_feedback'),
]

pis_employees/urls.py
from django.urls import re_path

from pis_employees.views import (
    AddNewEmployee, EmployeeListView,EmployeeDelete,EmployeeSalaryView,
    EmployeeSalaryDetail
)

urlpatterns = [
    re_path(r'^add/new/$', AddNewEmployee.as_view(), name='add_new_employee'),
    re_path(r'^list/$', EmployeeListView.as_view(),name='employee_list'),
    re_path(r'delete/(?P<pk>\d+)/$',EmployeeDelete.as_view(),name='delete_employee'),
    re_path(r'salary/(?P<pk>\d+)/$',EmployeeSalaryView.as_view(),name='employee_salary'),
    re_path(r'salary/(?P<pk>\d+)/detail/$',EmployeeSalaryDetail.as_view(),name='employee_salary_detail'),
]

pis_expense/urls.py
from django.urls import re_path


from pis_expense.views import (
    AddNewExpense,ExpenseListView,ExpenseDelete,dashboard
)

urlpatterns = [
    re_path(r'^add/new/$', AddNewExpense.as_view(), name='add_new_expense'),
    re_path(r'^list/$', ExpenseListView.as_view(),name='expense_list'),
    re_path(r'^dashboard/$', dashboard.as_view(),name='dashboard'),
    re_path(r'delete/(?P<pk>\d+)/$',ExpenseDelete.as_view(),name='delete_expense'),
]

templates/employee/create.html
{% extends 'base.html' %}
{% block submenu_create_employee %}active{% endblock %}
{% block menu_employee %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'expense:expense_list' %}"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Employee List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ request.user.retailer_user.retailer.name }} Add Employee</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'employee:add_new_employee' %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Name</strong></label>
                        <span class="name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control name" name="name" placeholder="Name"><br>
                        <label><strong>Father Name</strong></label>
                        <span class="father_name-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control father_name" name="father_name" placeholder="Father Name"><br>
                        <label><strong>mobile Number</strong></label>
                        <span class="mobile-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control mobile" name="mobile" placeholder="Mobile"><br>
                        <label><strong>Address</strong></label>
                        <textarea class="form-control address" name="address" placeholder="Address"></textarea><br>
                        <label><strong>Date of Joining</strong></label>
                        <input type="text" class="form-control date" name="date_of_joining" placeholder=" Date of joining" onfocus="(this.type='date')" onblur="(this.type='text')"><br>
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Employee</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
        $('document').ready(function () {

            $('.ledger-submit-btn').on ('click', function () {
                $(this).addClass('disabled');
                $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
                var error = false;

                if ($('.name').val() ==""){
                    $('.name-error').show();
                    error= true;
                }
                else {
                    $('.name-error').hide();
                }
                if ($('.father_name').val() ==""){
                    $('.father_name-error').show();
                    error= true;
                }
                else {
                    $('.father_name-error').hide();
                }
                 if ($('.mobile').val() =="" ) {
                    $('.mobile-error').show();
                    error = true;
                }
                else {
                    $('.mobile-error').hide();
                }
                if (error == true ) {
                    $(this).removeClass('disabled');
                    $(this).html('Save');
                    return;
                }

                if (error == false) {
                    $('.add-ledger-form').submit();
                }
                 else {
                     $(this).removeClass('disabled');
                     $(this).html('Save');
                     return;
                 }
            });

            $('.customer').keyup(function () {
                $('.customer-error').hide();
            });


            $('.customer_phone').keyup(function () {
               $('.customer-phone-error').hide();
               checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.amount').keyup(function () {
               $('.amount-error').hide();
                checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.description').keyup(function () {
                $('.description-error').hide();
            });
        });

    </script>
<script>

$('#empolyee').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>

{% endblock %}

templates/employee/employee_list.html
{% extends 'base.html' %}
{% block submenu_list_employee %}active{% endblock %}
{% block menu_employee %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br>
            <a href="{% url 'employee:add_new_employee' %}"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Create Employee</button></a>
            <br><br>
            <div class="content-panel table-responsive">
                <h2 class="text-center">Employee List</h2><div class="input-group custom-search-form col-md-4" style="left: 5px">
                <input type="text" class="form-control search-order" placeholder="Search...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
            </div>
                <hr>
                <table class="table table-striped table-advance table-hover item-table table-bordered">
                    <thead>
                    <tr>
                        <th class="text-center"><i class="fa fa-gavel"></i> S.No</th>
                        <th class="text-center"><i class="fa fa-gavel"></i> Name</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Father Name</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Mobile</th>
                        <th class="text-center"><i class="fa fa-bullhorn"></i>Address</th>
                        <th class="text-center"><i class=" fa fa-edit"></i> Date of Joining</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody class="order-table-body text-center">
                    {% for employee in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ employee.name }}</td>
                        <td>{{ employee.father_name }}</td>
                        <td>{{ employee.mobile }}</td>
                        <td>{{ employee.address }}</td>
                        <td>{{ employee.date_of_joining }}</td>
                        <td>
                            <a href="{% url 'employee:delete_employee' pk=employee.id %}"><button class="btn btn-danger btn-xs" title="Delete"><i class="fa  fa-trash-o"></i></button></a>
                            <a href="{% url 'employee:employee_salary' pk=employee.pk %}"><button class="btn btn-primary btn-xs" title="Salary"><i class="fa  fa-money"></i></button></a>
                            <a href="{% url 'employee:employee_salary_detail' pk=employee.pk %}"><button class="btn btn-info btn-xs" title="Employee Salary Record"><i class="fa fa-bar-chart-o"></i></button></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if is_paginated %}
                <div class="text-center">
                    <ul class="pagination" style="padding: 10px; margin: auto;">
                        {% for p in page_obj.paginator.page_range %}
                        <li {% if p == page_obj.number %}class="active"{% endif %}><a href="?page={{ p }}" data-original-title="" title="">{{ forloop.counter }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
        $(document).ready(function(){
          $(".search-order").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $(".order-table-body tr").filter(function() {
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
          });
        });
    </script>
<script>

$('#empolyee').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>
{% endblock %}

templates/employee/employee_salary.html
{% extends 'base.html' %}
{% block menu_employee %}active{% endblock %}
{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'employee:employee_list' %}"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Employee List</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">{{ request.user.retailer_user.retailer.name }} Add Employee</h3>
            <div class="panel-body">
                <form class="form-horizontal add-ledger-form" action="{% url 'employee:employee_salary' pk=employee.pk %}" method="post" autocomplete="off">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {% csrf_token %}
                            <label><strong>Name</strong></label>
                            <span class="name-error" style="color: red; display: none" >this field is requried</span>
                            <input type="text" class="form-control customer-name" name="employee_name"  value="{{employee.name}}" readonly> <br>
                            <label><strong>Salary</strong></label>
                            <span class="salary_amount-error" style="color: red; display: none" >this field is requried</span>
                            <input type="text" class="form-control salary_amount" name="salary_amount" placeholder="Salary Amount"><br>
                            <label><strong>Date</strong></label>
                            <span class="date-error" style="color: red; display: none" >this field is requried</span>
                            <input type="text" class="form-control date" name="date" placeholder=" Date" onfocus="(this.type='date')" onblur="(this.type='text')"><br>
                            <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                            <button type="button" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Salary</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $('document').ready(function () {

            $('.ledger-submit-btn').on ('click', function () {
                $(this).addClass('disabled');
                $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
                var error = false;

                if ($('.name').val() ==""){
                    $('.name-error').show();
                    error= true;
                }
                else {
                    $('.name-error').hide();
                }
                if ($('.salary_amount').val() ==""){
                    $('.salary_amount-error').show();
                    error= true;
                }
                else {
                    $('.salary_amount-error').hide();
                }
                if ($('.date').val() ==""){
                    $('.date-error').show();
                    error= true;
                }
                else {
                    $('.date-error').hide();
                }
                if (error == true ) {
                    $(this).removeClass('disabled');
                    $(this).html('Save');
                    return;
                }

                if (error == false) {
                    $('.add-ledger-form').submit();
                }
                 else {
                     $(this).removeClass('disabled');
                     $(this).html('Save');
                     return;
                 }
            });

            $('.customer').keyup(function () {
                $('.customer-error').hide();
            });


            $('.customer_phone').keyup(function () {
               $('.customer-phone-error').hide();
               checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.salary_amount').keyup(function () {
               $('.salary_amount-error').hide();
                checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.date').keyup(function () {
                $('.date-error').hide();
            });
        });

    </script>
<script>

$('#empolyee').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>

{% endblock %}

templates/employee/employee_salary_detail.html
{% extends 'base.html' %}
{% block menu_employee %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'employee:employee_list' %}"><button type="button" id="empolyee" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Employee List</button></a>
    <a href="{% url 'employee:employee_salary' pk=employee.pk %}"><button type="button" id="empolyee-pay" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Do Payment</button></a>
    <br><br><br>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading text-center">
                    <span>{{ employee.name }} Employee Salary Details</span>
                </div>
        {% if salaries %}
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-advance table-hover ledger-table table-responsive table-bordered">
                        <thead>
                        <tr>
                            <th class="text-center"><i class="fa fa-bullhorn"></i> Amount</th>
                            <th class="text-center"><i class="fa fa-bookmark"></i> Date</th>
                        </tr>
                        </thead>
                        <tbody class="item-table-body text-center">
                        {% for salary in salaries %}
                        <tr>
                            <td>{{ salary.salary_amount|floatformat:-2}}</td>
                            <td>{{ salary.date }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
<script>

$('#empolyee').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('#empolyee-pay').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>

    {% endblock %}