partum_inventory/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^', include('pis_com.urls')),
    re_path(r'^product/', include(('pis_product.urls', 'product'),namespace='product'),),
    re_path(r'^retailer/', include(('pis_retailer.urls', 'retailer'), namespace='retailer')),
    re_path(r'^sales/', include(('pis_sales.urls', 'sales'), namespace='sales')),
    re_path(r'^ledger/', include(('pis_ledger.urls','ledger'), namespace='ledger')),
    re_path(r'^expense/', include(('pis_expense.urls','expense'), namespace='expense')),
    re_path(r'^employee/', include(('pis_employees.urls','employee'), namespace='employee')),
    re_path(r'^supplier/', include(('pis_supplier.urls','supplier'), namespace='supplier')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pis_com/urls.py
from django.urls import path, include,re_path


from pis_com.views import HomePageView
from pis_com.views import LoginView
from pis_com.views import LogoutView
from pis_com.views import (
    CreateCustomer, CustomerTemplateView, CustomerUpdateView, CreateFeedBack)
from pis_com.views import RegisterView, ReportsView

urlpatterns = [
    re_path(r'^$', HomePageView.as_view(), name='index'),
    re_path(r'^reports/$', ReportsView.as_view(), name='reports'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    #path('api/', include('pis_com.api_urls', namespace='com_api')),
    re_path(r'^api/',CreateCustomer.as_view(),name='create_customer'),

    re_path(r'^customer/create/$', CustomerTemplateView.as_view(), name='customers'),

    re_path(r'^customers/$', CustomerUpdateView.as_view(), name='update_customer'),
    re_path(r'^customer/(?P<pk>\d+)/update$', RegisterView.as_view(), name='register'),
    re_path(r'^register/$', CreateFeedBack.as_view(), name='create_feedback'),
]

pis_ledger/urls.py
from django.urls import re_path

from pis_ledger.views import (
    CustomerLedgerView, AddNewLedger, AddLedger,
    CustomerLedgerDetailsView,AddPayment
)

urlpatterns = [
    re_path(r'^add/new/$', AddNewLedger.as_view(), name='add_new_ledger'),
    re_path(r'^list/customer/$', CustomerLedgerView.as_view(),name='customer_ledger_list'),
    re_path(r'^add/customer/(?P<customer_id>\d+)/ledger/$',AddLedger.as_view(),name='add_ledger'),
    re_path(r'^add/customer/(?P<customer_id>\d+)/payment/$',AddPayment.as_view(),name='add_payment'),
    re_path(r'^customer/(?P<customer_id>\d+)/ledger/details/$',CustomerLedgerDetailsView.as_view(),name='customer_ledger_detail'),
]

templates/ledger/add_customer_ledger.html
{% extends 'base.html' %}
{% block menu_ledger %}active{% endblock %}
{% block submenu_customer_ledger %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'ledger:customer_ledger_list'%}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Ledger List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ customer.customer_name }} <small>New Ledger</small></h3>
        <div class="panel-body">
            <form class="form-horizontal new_ledger" action="{% url 'ledger:add_ledger' customer_id=customer.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Amount</strong></label>
                        <span class="amount-error" style="color: red; display: none" >This Field is Requried</span>
                        <input type="text" class="form-control amount" name="amount" placeholder="Amount"><br>
                        <label><strong>Date</strong></label>
                        <span class="date-error" style="color: red; display: none" >This Field is Requried</span>
                        <input type="date" class="form-control date" name="dated"><br>
                        <label><strong>Description</strong></label>
                        <span class="description-error" style="color: red; display: none" >This Field is Requried</span>
                        <textarea maxlength="500" rows="4" name="description" class="form-control description"  placeholder ="Description"></textarea> <br>
                        <input type="hidden" name="customer" value="{{ customer.id }}">
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Ledger</button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
        $('.document').ready(function () {
            $('.ledger-submit-btn').on('click', function () {
                $(this).addClass('disabled');
               $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
                 var error= false;

                if ($('.amount').val() ==""){
                    $('.amount-error').show();
                    error = true;
                }
                else {
                    $('.amount-error').hide();
                }
                if ($('.date').val() ==""){
                    $('.date-error').show();
                    error = true;
                }
                else {
                    $('.date-error').hide();
                }
                if ($('.description').val() == ""){
                    $('.description-error').show();
                    error = true;
                }
                else {
                    $('.description-error').hide();

                }
                if (error == false){
                    $('.new_ledger').submit();
                }
                 else
                 {
                     $(this).removeClass('disabled');
                     $(this).html('Save Ledger');
                     return;
                 }

            });
        });

            $('.amount').keyup(function () {
                $('.amount-error').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
            $('.description').keyup(function () {
                $('.description-error').hide();
            });


    </script>
<script>
$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});
    </script>

{% endblock %}

templates/ledger/add_payment.html
{% extends 'base.html' %}
{% block menu_ledger %}active{% endblock %}
{% block submenu_customer_ledger %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'ledger:customer_ledger_list'%}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Ledger List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ customer.customer_name }} <small>New Ledger</small></h3>
        <div class="panel-body">
            <form class="form-horizontal new_ledger" action="{% url 'ledger:add_payment' customer_id=customer.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Payment Amount</strong></label>
                        <span class="amount-error" style="color: red; display: none" >This Field is Requried</span>
                        <input type="text" class="form-control amount" name="payment" placeholder="Payment Amount"><br>
                        <label><strong>Date</strong></label>
                        <span class="date-error" style="color: red; display: none" >This Field is Requried</span>
                        <input type="date" class="form-control date" name="dated"><br>
                        <label><strong>Description</strong></label>
                        <span class="description-error" style="color: red; display: none" >This Field is Requried</span>
                        <textarea maxlength="500" rows="4" name="description" class="form-control description"  placeholder ="Description"></textarea> <br>
                        <input type="hidden" name="customer" value="{{ customer.id }}">
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Ledger</button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
        $('.document').ready(function () {
            $('.ledger-submit-btn').on('click', function () {
                $(this).addClass('disabled');
               $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
                 var error= false;

                if ($('.amount').val() ==""){
                    $('.amount-error').show();
                    error = true;
                }
                else {
                    $('.amount-error').hide();
                }
                if ($('.date').val() ==""){
                    $('.date-error').show();
                    error = true;
                }
                else {
                    $('.date-error').hide();
                }
                if ($('.description').val() == ""){
                    $('.description-error').show();
                    error = true;
                }
                else {
                    $('.description-error').hide();

                }
                if (error == false){
                    $('.new_ledger').submit();
                }
                 else
                 {
                     $(this).removeClass('disabled');
                     $(this).html('Save Ledger');
                     return;
                 }

            });
        });

            $('.amount').keyup(function () {
                $('.amount-error').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
            $('.description').keyup(function () {
                $('.description-error').hide();
            });


    </script>
<script>
$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});
    </script>

{% endblock %}

templates/ledger/create_ledger.html
{% extends 'base.html' %}
{% block submenu_add_new_ledger %}active{% endblock %}
{% block menu_ledger %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'ledger:customer_ledger_list' %}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Ledger List</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ request.user.retailer_user.retailer.name }} Customer / Ledger</h3>
        <div class="panel-body">
            <form class="form-horizontal add-ledger-form" action="{% url 'ledger:add_new_ledger' %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                        <label><strong>Customer Name</strong></label>
                        <span class="customer-existing" style="color: red; display: none" >Customer Already Exisit</span>
                        <span class="customer-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control customer" name="customer_name" placeholder="Name"><br>
                        <label><strong>Customer phone</strong></label>
                        <span class="customer-phone-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control customer_phone" name="customer_phone" placeholder="Phone"><br>
                        <label><strong>Customer Type</strong></label>
                        <span class="customer-type-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control customer_type" name="customer_type" placeholder="Person Type">
                        <span style="color:#00ccff">For example: Retailer, WholeSale Dealer etc</span><br><br>
                        <label><strong>Amount</strong></label>
                        <span class="amount-error" style="color: red; display: none" >this field is requried</span>
                        <input type="text" class="form-control amount" name="amount" placeholder="Amount"><br>
                        <label><strong>Description</strong></label>
                        <span class="description-error" style="color: red; display: none" >this field is requried</span>
                        <textarea maxlength="500" rows="4" name="description" class="form-control description"  placeholder ="Description"></textarea> <br>
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" id="save" class="btn btn-primary ledger-submit-btn" style="float: right" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing Order">Save Ledger</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
        $('document').ready(function () {

            $('.ledger-submit-btn').on ('click', function () {
                $(this).addClass('disabled');
                $(this).html('<i class="fa fa-circle-o-notch fa-spin"></i> Loading...');
                var error = false;

                if ($('.customer').val() ==""){
                    $('.customer-error').show();
                    error= true;
                }
                else {
                    $('.customer-error').hide();
                }
                if ($('.customer_phone').val() ==""){
                    $('.customer-phone-error').show();
                    error= true;
                }
                else {
                    $('.customer-phone-error').hide();
                }
                if ($('.customer_type').val() ==""){
                    $('.customer-type-error').show();
                    error= true;
                }
                else {
                    $('.customer-type-error').hide();
                }

                if ($('.amount').val() =="" ) {
                    $('.amount-error').show();
                    error = true;
                }
                else {
                    $('.customer-error').hide();
                }
                if ($('.description').val()== ""){
                    $('.description-error').show();
                    error =true ;
                }
                else {
                    $('.description-error').hide();
                }
                if (error == true ) {
                    $(this).removeClass('disabled');
                    $(this).html('Save');
                    return;
                } else {
                    {% for customer in customers %}
                        if ($('.customer_phone').val()== '{{ customer.customer_phone }}') {
                            $('.customer-existing').show();
                            return;
                        }
                    {% endfor %}
                }

                if (error == false) {
                    $('.add-ledger-form').submit();
                }
                 else {
                     $(this).removeClass('disabled');
                     $(this).html('Save Ledger');
                     return;
                 }
            });

            $('.customer').keyup(function () {
                $('.customer-error').hide();
            });


            $('.customer_phone').keyup(function () {
               $('.customer-phone-error').hide();
               checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.amount').keyup(function () {
               $('.amount-error').hide();
                checkDec(this);
            });
            function checkDec(el){
            var ex = /^[0-9]+\.?[0-9]*$/;
            if(ex.test(el.value)==false){
                el.value = el.value.substring(0,el.value.length - 1);
            }
        }
            $('.customer_type').keyup(function () {
                $('.customer-type-error').hide();
            });
            $('.description').keyup(function () {
                $('.description-error').hide();
            });
        });

    </script>
<script>

$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>

{% endblock %}

templates/ledger/customer_ledger_details.html
{% extends 'base.html' %}
{% block menu_ledger %}active{% endblock %}
{% block submenu_customer_ledger %}active{% endblock %}

{% block content %}
<br>
<a href="{% url 'ledger:customer_ledger_list'%}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Ledger List</button></a>
<a href="{% url 'ledger:add_ledger' customer_id=customer.id %}"><button type="button" id="ledger-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add New Ledger</button></a>
<a href="{% url 'ledger:add_payment' customer_id=customer.id %}"><button type="button" id="payment-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add payment</button></a>
<br><br><br>
<div class="container-fluid">
    <div class="row">
        <div class="content-panel">
            <div class="panel-body table-responsive">
            <h2 class="text-center">{{ customer.customer_name|title }} <small>Ledger Detail</small></h2>
            {% if ledgers %}
            <div class="col-lg-12 col-md-12 col-sm-12">
                        <div style="float: right; padding: 12px; font-size: 20px">
                            <strong style="float: right">Total Remaining Amount: <span style="color: red">{{ remaining_amount|floatformat:-2 }}</span></strong>
                        </div>
                        <hr>
                        <table class="table table-striped table-advance table-bordered table-hover ledger-table table-responsive">
                            <thead>
                            <tr>
                                <th class="text-center">Date</th>
                                <th class="text-center">Amount</th>
                                <th class="text-center">Payment Amount</th>
                                <th class="text-center">Invoice</th>
                                <th class="text-center">Description</th>
                            </tr>
                            </thead>
                            <tbody class="item-table-body text-center">
                            {% for ledger in ledgers %}
                            <tr>
                                <td>{{ ledger.dated }}</td>
                                <td>{{ ledger.amount|floatformat:-2}}</td>
                                <td>{{ ledger.payment|floatformat:-2}}</td>
                                <td>{{ ledger.invoice.receipt_no }}</td>
                                <td>{{ ledger.description }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script>
$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

$('#do-pay').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});
    </script>
{% endblock %}

templates/ledger/customer_ledger_list.html
{% extends 'base.html' %}
{% block menu_ledger %}active{% endblock %}
{% block submenu_customer_ledger %}active{% endblock %}

{% block content %}
<div class="col-md-12">
    <br>
    <a href="{% url 'ledger:add_new_ledger' %}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Add New</button></a>
    <br><br><br>
    <div class="content-panel table-responsive">
        <table class="table table-striped table-advance table-hover table-bordered purchased-table">
            <h2 class="text-center">Customer Ledger</h2>
            <div class="input-group custom-search-form col-md-4" style="left: 5px">
                <input type="text" class="form-control extra-items" placeholder="Search...">
                <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
            </div>
            <div style="float: right; padding: 12px; font-size: 20px">
                <strong>Total Remaining Amount: </strong><span style="color: red">{{ total_remaining_amount|floatformat:'-2' }}</span>
            </div>
            <hr>
            <thead>
            <tr>
                <th class="text-center"><i class="fa fa-bullhorn"></i> Name</th>
                <th class="text-center"><i class=" fa fa-bookmark"></i> Phone</th>
                <th class="text-center"><i class=" fa fa-bookmark"></i> Person Type</th>
                <th class="text-center"><i class=" fa fa-edit"></i> Total Ledger</th>
                <th class="text-center"><i class=" fa fa-edit"></i> Total Payment</th>
                <th class="text-center"><i class=" fa fa-bookmark"></i> Remaining Ledger</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody class="ledger-table-body text-center">
            {% if customer_ledgers %}
            {% for customer_ledger in customer_ledgers %}
            <tr>
                <td><a href="{% url 'ledger:customer_ledger_detail' customer_id=customer_ledger.id %}">{{ customer_ledger.customer_name}}</a></td>
                <td>{{ customer_ledger.customer_phone }}</td>
                <td>{{ customer_ledger.customer_type}}</td>
                <td>{{ customer_ledger.ledger_amount|floatformat:-2 }}</td>
                <td>{{ customer_ledger.payment_amount|floatformat:-2 }}</td>
                <td>{{ customer_ledger.remaining_ledger|floatformat:-2 }}</td>
                <td>
                    <a href="{% url 'ledger:customer_ledger_detail' customer_id=customer_ledger.id %}"><button class="btn btn-success btn-xs" title="Customer Ledger Detail"><i class="fa fa-eye"></i></button></a>
            </tr>
            {% endfor %}
            {% else %}
            <tr><td colspan="6" class="text-center">No Record Found</td></tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
<script>
       $(document).ready(function(){
          $('.extra-items').on("keyup", function() {
              var value = $(this).val().toLowerCase();
              $(".ledger-table-body tr").filter(function() {
                 $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
              });
          });
       })

    </script>
<script>

$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>
{% endblock %}

templates/ledger/payment_ledger.html
{% extends 'base.html' %}
{% block menu_ledger %}active{% endblock %}
{% block submenu_customer_ledger %}active{% endblock %}
{% block content %}
<div class="col-md-6">
    <br>
    <a href="{% url 'ledger:customer_ledger_detail' customer_id=customer.id%}"><button type="button" id="back-customer" class="btn btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i>Processing">Customer Ledger Details</button></a>
    <br><br><br>
    <div class="content-panel">
        <h3 class="text-center">{{ customer.customer_name }} <small>Payment</small></h3>
        <div class="panel-body">
            <form class="form-horizontal add-payment" action="{% url 'ledger:payment_ledger' customer_id=customer.id %}" method="post" autocomplete="off">
                <div class="form-group">
                    <div class="col-sm-12">
                        {% csrf_token %}
                         <label><strong>Amount</strong></label>
                        <span class="amount-error" style="color: red; display: none"> This Feild is Requried</span>
                        <input type="text" class="form-control amount" name="amount" placeholder="Amount"><br>
                        <label><strong>payment Type</strong></label>
                        <input type="text" class="form-control payment_type" name="payment_type" placeholder="Payment Type">
                        <span style="color: #68dff0">For example: UBL Online, HBL Check or Cash etc</span><br><br>
                        <label><strong>Description</strong></label>
                        <textarea placeholder="Description" name="description" class="form-control description"></textarea><br>
                        <input type="hidden" name="customer" value="{{ customer.id }}">
                        <input type="hidden" name="retailer" value="{{ request.user.retailer_user.retailer.id }}">
                        <button type="button" class="btn btn-primary ledger-submit-btn" style="float: right">Save Ledger</button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
        $('.document').ready ( function() {
            $('.ledger-submit-btn').on('click', function(){
                var error = false;
                if ($('.amount').val ()== ""){
                    $('.amount-error').show();
                    error = true;
                }
                else {
                    $('.amount-error').hide();
                }
                if (error == false){
                    $('.add-payment').submit();
                }

                $('.amount').keyup(function () {
                    $('.amount-error').hide();
                    checkDec(this);
                });
                function checkDec(el){
                    var ex = /^[0-9]+\.?[0-9]*$/;
                    if(ex.test(el.value)==false){
                        el.value = el.value.substring(0,el.value.length - 1);
                    }
                }

            });
        });

    </script>
<script>

$('#back-customer').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

    </script>
{% endblock %}